#!/usr/bin/env python

import os
import redis
from rq import Worker, Queue, Connection
from ioos_catalog import redis_connection
import logging

logging.basicConfig(level=logging.INFO)

listen = ['default']

with Connection(redis_connection):
    worker = Worker(map(Queue, listen))
    worker.work()
